#       $OpenBSD: dhcpd.conf,v 1.1 2014/07/11 21:20:10 deraadt Exp $
#
# DHCP server options.
# See dhcpd.conf(5) and dhcpd(8) for more information.
#

# Network:              192.168.1.0/255.255.255.0
# Name servers:         192.168.1.1, 1.1.1.1 and 8.8.8.8
# Default router:       192.168.1.1
# Addresses:            192.168.1.32 - 192.168.1.127

subnet 192.168.1.0 netmask 255.255.255.0 {
        option routers 192.168.1.1;

        option domain-name-servers 192.168.1.1, 1.1.1.1, 8.8.8.8;

        host nas {
                fixed-address 192.168.1.2;
                # nas's re0's MAC address with switch0 on nas
                hardware ethernet 00:0d:b9:32:fd:68;
                # nas's vether0's MAC address with bridge0 on nas
                # hardware ethernet fe:e1:ba:d0:78:d7;
        }
        
        range 192.168.1.32 192.168.1.127;
                
}
