subnet 192.168.1.0 netmask 255.255.255.0 {
        option routers 192.168.1.1;

        option domain-name-servers 192.168.1.1, 1.1.1.1, 8.8.8.8;

        host nas {
                fixed-address 192.168.1.2;
                # nas's re0's MAC address with switch0 on nas
                hardware ethernet 00:0d:b9:32:fd:68;
        }
        
        range 192.168.1.32 192.168.1.127;
                
}
