server:
        interface: 192.168.1.1
        interface: 127.0.0.1
        access-control: 192.168.1.0/24 allow
        do-not-query-localhost: no
        hide-identity: yes
        hide-version: yes

        # LAN is called k9w.
        local-zone: "k9w" static

        # Local DNS A records.
        local-data:  "router    IN A    192.168.1.1"
        local-data:     "nas    IN A    192.168.1.2"

        # Local Reverse DNS records.
        local-data-ptr: "192.168.1.1            router"
        local-data-ptr: "192.168.1.2            nas"


forward-zone:
        name: "."
        forward-addr: 8.8.8.8  # IP of the upstream resolver
